id: PA5A08642
initial_creation_type: ocr
source_metadata:
  volumes:
    3d6111e1c2494c56bf5587ab9ea91a93:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
